"""Schemas 包."""

from paper_plane_x_backend.schemas.agent_io import (
    AssistantMessage,
    Citation,
    CitedText,
    ExtractionAgentOutput,
    ExtractionAgentUserInput,
    FactCheckAgentOutput,
    FactCheckAgentUserInput,
    FactCheckError,
    KeyResults,
    Methodology,
    QuickScan,
    ResearchGap,
    SynthesisData,
    SystemMessage,
    ToolCallMessage,
    UserMessage,
)
from paper_plane_x_backend.schemas.api import (
    DataProcessManualUpdateRequest,
    DataProcessRequest,
    DataProcessSubmitResponse,
    DataProcessTaskListResponse,
    DataProcessTaskResponse,
    ErrorResponse,
    LibrarianConditionGroup,
    LibrarianConditionPredicate,
    LibrarianMatrixRequest,
    LibrarianMatrixResponse,
    LibrarianProjectionRequest,
    LibrarianProjectionResponse,
    LibrarianUnifiedSearchRequest,
    LibrarianUnifiedSearchResponse,
    MessageResponse,
    PaperDetailResponse,
    PaperListResponse,
    PaperResponse,
    ProjectCreateRequest,
    ProjectListResponse,
    ProjectResponse,
    ProjectUpdateRequest,
)

__all__ = [
    # API Schemas
    "DataProcessSubmitResponse",
    "DataProcessTaskListResponse",
    "DataProcessTaskResponse",
    "DataProcessManualUpdateRequest",
    "DataProcessRequest",
    "ErrorResponse",
    "LibrarianConditionGroup",
    "LibrarianConditionPredicate",
    "LibrarianMatrixRequest",
    "LibrarianMatrixResponse",
    "LibrarianProjectionRequest",
    "LibrarianProjectionResponse",
    "LibrarianUnifiedSearchRequest",
    "LibrarianUnifiedSearchResponse",
    "MessageResponse",
    "PaperDetailResponse",
    "PaperListResponse",
    "PaperResponse",
    "ProjectCreateRequest",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectUpdateRequest",
    # Message Schemas
    "AssistantMessage",
    "SystemMessage",
    "ToolCallMessage",
    "UserMessage",
    # Agent IO Schemas
    "Citation",
    "CitedText",
    "QuickScan",
    "ResearchGap",
    "Methodology",
    "KeyResults",
    "SynthesisData",
    "FactCheckError",
    "ExtractionAgentUserInput",
    "ExtractionAgentOutput",
    "FactCheckAgentUserInput",
    "FactCheckAgentOutput",
]
